<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<title>Jane Butzner Jacobs | Nathan Milner</title>
		<link href="style.css" rel="stylesheet" type="text/css">
		<link href="https://fonts.googleapis.com/css?family=Raleway:400,700|Bitter:400,700" rel="stylesheet"> 
		<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css" rel="stylesheet">
		<?php include_once("analyticstracking.php") ?>
	</head>
	<body>
  <div id="main">
	<div id="stage">
		<div class="intwrap blue">
			<div id="title" class="blue">
				<h2>Exploring the Piazza dell&rsquo;Arte: Jane Jacobs</h2>
			</div>
			<p><img class="alignright" style="border: 0pt none; margin: 3px; float: right;" src="images/jacobs2.jpg" alt="Jane Jacobs" width="184" height="249" />We continue exploring the lives and works of the artists featured on the Piazza dell’Arte at Scranton’s Courthouse Square today with a profile of one of America&#8217;s most noted urban planners Jane Butzner Jacobs.</p>
			<p>Jacobs was born May 4, 1916, in Scranton and attended Scranton Central High School. After graduation, she began an unpaid position as the assistant to the women&#8217;s page editor at the Scranton Tribune (now <a title="The Times-Tribune" href="http://www.thetimes-tribune.com/" target="_blank">The Times-Tribune</a>) before the onset of the Great Depression forced her to leave Scranton for New York City.</p>
			<p>The move to New York would <a title="Jacobs and New York" href="http://www.futureofny.org/home" target="_blank">shape Jacobs’ career </a>and interest in urban development. She took jobs working as a stenographer and as a freelance writer, often writing about working districts in the city. Jacobs eventually became the editor of a trade magazine, working her way up from secretary, before becoming a feature writer for the <a title="Office of War Information" href="http://en.wikipedia.org/wiki/Office_of_War_Information" target="_blank">Office of War Information</a>, where she met architect Robert Hyde Jacobs. The couple was married in 1944 and they would have two sons and a daughter together.</p>
			<p><img class="alignleft" style="border: 0pt none; margin: 3px; float: left;" src="images/deathandlife.JPG" alt="Death and Life of American Cities" width="168" height="254" />In 1961, Jacobs produced her most influential book, <a title="The Death and Life of Great American Cities" href="http://en.wikipedia.org/wiki/The_Death_and_Life_of_Great_American_Cities" target="_blank">“The Death and Life of Great American Cities.”</a> Still considered one of the finest American works on urban planning and cities, “The Death and Life of Great American Cities” critiques the urban renewal policies of the 1950s, claiming they destroyed communities with isolated, unnatural urban spaces. Jacobs, in contrast, supported dense, mixed-use neighborhoods and bolstered her claims with a theoretical approach that incorporated both solid data and subjective, intuitive observation.</p>
			<p>She chaired the successful Joint Committee to Stop the <a title="Lower Manhattan Expressway" href="http://en.wikipedia.org/wiki/Lower_Manhattan_Expressway" target="_blank">Lower Manhattan Expressway</a> in 1962 and would oppose expressways in favor of neighborhoods throughout her life. In another attempt to stop the Lower Manhattan Expressway in 1968, she was arrested during a demonstration.</p>
			<p><img class="alignright" style="border: 0pt none; margin: 3px; float: right;" src="images/jacobs.jpg" alt="Jacobs protests" width="310" height="275" />The same year, Jacobs moved to Toronto in part because of her objection to the Vietnam War and to protect her two draft-age sons; she would become a Canadian citizen in 1974. While living in Toronto, she helped stop the proposed <a title="Spadina Expressway" href="http://en.wikipedia.org/wiki/Spadina_Expressway" target="_blank">Spadina Expressway</a>, was arrested twice during demonstrations and led the regeneration of the St. Lawrence neighborhood.</p>
			<p>Jacobs published her second book, &#8220;The Economy of Cities,&#8221; in 1969 which included the arguments that cities are the primary drivers of economic development and that all economic growth derives from “import replacement” &#8212; a phrase that refers to a city producing locally goods that it formerly imported.</p>
			<p>She helped found the <a title="Energy Probe Research Foundation" href="http://www.eprf.ca/" target="_blank">Energy Probe Research Foundation</a>, an environmental organization that demonstrated the environmental advantages inherent in cities and city life, in the late 1970s. She remained active with the group as a director until her retirement in the late 1990s and helped change public attitudes towards cities, showcasing their environmental advantages.</p>
			<p>Jacobs advocated Toronto separating from the city of Ontario and published her perspective on Québec&#8217;s sovereignty in her book “The Question of Separatism: Quebec and the Struggle over Separation” in 1980.</p>
			<p>Her contribution to urban planning and development in and around Toronto led to her being selected as an officer of the <a title="Order of Canada" href="http://en.wikipedia.org/wiki/Order_of_Canada" target="_blank">Order of Canada</a> in 1996; and in 1997, Toronto sponsored a conference titled <a title="Ideas That Matter" href="http://www.ideasthatmatter.com/" target="_blank">&#8220;Jane Jacobs: Ideas That Matter,”</a> which culminated in the presentation of the <a title="Jane Jacobs prize" href="http://www.ideasthatmatter.com/people/index.phtml" target="_blank">Jane Jacobs Prize</a> to be given to &#8220;celebrate Toronto&#8217;s original, unsung heroes — by seeking out citizens who are engaged in activities that contribute to the city&#8217;s vitality.” The <a title="Community and Urban Sociology section" href="http://www.commurb.org/" target="_blank">Community and Urban Sociology section of the American Sociological Association</a> awarded Jacobs its Outstanding Lifetime Contribution award in 2002.</p>
			<p>S<img class="alignright" style="border: 0pt none; margin: 3px; float: right;" src="images/jacobsmedal.jpg" alt="Jacobs medal" width="127" height="130" />he died in Toronto Western Hospital at the age of 89, on April 25, 2006, apparently of a stroke but her legacy <a title="Jacobs' legacy" href="http://purejuice.livejournal.com/743169.html" target="_blank">lives on</a>. <a title="The Rockefeller Foundation" href="http://en.wikipedia.org/wiki/Rockefeller_Foundation" target="_blank">The Rockefeller Foundation</a> announced on February 9, 2007, the creation of the <a title="Jane Jacobs medal" href="http://www.rockfound.org/efforts/jacobs/janejacobs.shtml" target="_blank">Jane Jacobs Medal</a>, &#8220;to recognize individuals who have made a significant contribution to thinking about urban design, specifically in New York City.&#8221;</p>
			<p>The City of Toronto proclaimed Friday May 4, 2007 as Jane Jacobs Day in Toronto. Two dozen free &#8220;<a title="Jane's Walk" href="http://www.janeswalk.net/" target="_blank">Jane&#8217;s Walks</a>&#8221; were held around Toronto neighborhoods on May 5, 2007. A Jane&#8217;s Walk event was held in New York in on September 29 and 30, 2007 and, this year, the event has spread to eight cities and towns across Canada.</p>
			<p><strong>Spiritual Heir:</strong> Dan Brennan. While not involved in Scranton’s urban planning in an official capacity, Brennan has shown as much dedication to the renewal of this city as Jacobs did New York and Toronto. As the editor and publisher of <a title="The Antenna" href="http://www.scrantenna.com" target="_blank">The Antenna magazine</a>, Brennan has celebrated the best of Scranton and pointed out the areas of the city’s structure that could use improvement. Jacobs advocated the development of thriving urban communities in the style of New York&#8217;s <a title="Greenwich Village" href="http://www.nycgv.com/" target="_blank">Greenwich Village</a>. Last month, Brennan organized Scranton&#8217;s first-ever art festival, <a title="Scranhattan wrap up" href="http://www.electriccityr.com/scranhattan-first-friday" target="_blank">the Scranhattan Festival</a>; it was an event that surely would have made Jacobs proud of her hometown.</p>
		</div>
	</div>
	
	<?php include_once("sidebar-writing.php") ?>
    
  </div>
  <script src="http://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

</body>
</html>
